version: "3.9"
services: 
  db:
    container_name: sql-server
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      SA_PASSWORD: "fakePassw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes: 
      - "./data-db/data:/var/opt/mssql/data"
      - "./data-db/logs:/var/opt/mssql/log"
      - "./data-db/secrets:/var/opt/mssql/secrets"
  app:
    build: 
      context: ./app
    container_name: python-app
    volumes: 
      - "./app:/usr/src/app"